version: '2'

services:

    consul:
        image:  gliderlabs/consul-server:latest
        command: "-server -bootstrap"
        container_name: consul
        hostname: consul
        ports:
            - 8500:8500

    registrator:
        image: gliderlabs/registrator:latest
        command: "-internal consul://consul:8500"
        container_name: registrator
        hostname: registrator
        depends_on:
            - consul
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock

    consul-template:
        build: consul-template
        container_name: consul-template
        hostname: consul-template
        restart: always

        command: >
            -consul consul:8500
            -template "/etc/consul-template/nginx/nginx.conf.ctmpl:/etc/nginx/nginx.conf:. /etc/consul-template/nginx/reload-nginx.sh"

        volumes:
            - ./consul-template/templates:/etc/consul-template
            - ./etc:/etc/nginx
            - /var/run/docker.sock:/tmp/docker.sock
        
        environment: 
            - NGINX_CONTAINER=nginx-bot

        depends_on: 
            - consul

    nginx:
        image: umputun/nginx-le:latest
        container_name: nginx-bot
        hostname: nginx-bot
        restart: always

        logging: &default_logging
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/conf:/etc/nginx/

        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=America/Chicago
            - LETSENCRYPT=$LETSENCRYPT
            - SSL_KEY=$SSL_KEY
            - SSL_CERT=$SSL_CERT
            - LE_EMAIL=umputun@gmail.com
            - LE_FQDN=bot.radio-t.com

        depends_on:
            - consul-template
            - memberberries
            - hello

    hello:
        build: hello
        image: rtbot/hello-bot
        container_name: hello-bot
        hostname: hello-bot
        restart: always
        logging: *default_logging
        labels: 
            - SERVICE_TAGS=bot

    memberberries:
        build: memberberries
        image: rtbot/memberberries
        container_name: memberberries-bot
        hostname: memberberries-bot
        restart: always
        logging: *default_logging
        labels: 
            - SERVICE_TAGS=bot
